### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by yoneth** [justjavac/layoutit#1]
What is the license of layoutit ? 
Can I use this on my commercial product ?

**Comment by justjavac** [comment]
http://www.layoutit.com/

**Comment by howardroark2018** [comment]
I don't mean to offend anyone, but I wonder if the inquirer ever could find out the license for this project and its commercial friendliness.., and honestly, I couldn't find any details of the license at any of the prominant places, wherever I tried. Also, honestly, the way the question/issue was answered comes out to be one of the most pathetic & lazy (as well as indifferent ) ways to help someone. Anyways, I wonder about the chances of getting the same query 'answered', (as I also have the same question); at the same time, chosing to be hopeful for a rather simple/straightforward answer (instead of vague links etc.).

Thanks!
